feeder: dataset.dataloader_video.BaseFeeder
phase: train
dataset: phoenix14
# dataset: phoenix14-si5
num_epoch: 60
work_dir: ./work_dir/baseline_res18/
batch_size: 2
random_seed: 0
test_batch_size: 2
num_worker: 4
device: 0,1
log_interval: 50
eval_interval: 1
save_interval: 1
# python in default
evaluate_tool: sclite
loss_weights:
  # DecoderReg: 100.0
  # DecoderCTC: 1.0
  SeqCTC: 1.0
  # VAC
  ConvCTC: 1.0
  Dist: 10.0
  # Add
  SimsiamAlign: 1.0
  # LenPred: 1.0
  CADecoder: 1.0
  Conv1dCircle: 1.0
#load_weights: ''

optimizer_args:
  optimizer: Adam
  base_lr: 0.0001
  step: [ 20, 35]
  learning_ratio: 1
  weight_decay: 0.0001
  start_epoch: 0
  nesterov: False

feeder_args:
  mode: 'train'
  datatype: 'video'
  num_gloss: -1
  drop_ratio: 1.0
  proposal_num: 4
  max_label_len: 30

model: slr_network.SLRModel
decode_mode: beam
model_args:
  num_classes: 1296
  c2d_type: resnet50
  conv_type: 3
  use_bn: 1
  # SMKD
  share_classifier: True
  weight_norm: True
  proposal_num: 4
  max_label_len: 30
